openapi: 3.0.3
info:
  title: Swagger WeRec - OpenAPI 3.0
  description: ""
  termsOfService: http://swagger.io/terms/
  version: 1.0.1
externalDocs:
  description: Find out more
  url: https://github.com/hse-wasd-team/werec/wiki/About
servers:
- url: /api/v1/
tags:
- name: feed
  description: Feed managment
- name: video
  description: Get videos
paths:
  /videos/{feedId}/{keyword}/:
    get:
      tags:
      - video
      summary: Get videos
      description: Returns an array of video links
      operationId: getVideosByFeedId
      parameters:
      - name: feedId
        in: path
        description: ID of feed
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: keyword
        in: path
        description: keyword
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Returns list of video links
          content:
            application/json:
              schema:
                type: array
                example:
                - https://www.youtube.com/watch?v=o1YenjwOp-A
                - https://www.youtube.com/watch?v=cjO_yorTfP8
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Invalid feed id or keyword supplied
        "404":
          description: Feed or keyword not found
      x-swagger-router-controller: Video
  /feed/{feedId}:
    get:
      tags:
      - feed
      summary: Get feed information by id
      description: Returns feed information
      operationId: getFeedById
      parameters:
      - name: feedId
        in: path
        description: ID of the feed that needs to be altered
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Returns feed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
        "400":
          description: Invalid ID supplied
        "404":
          description: Feed not found
      x-swagger-router-controller: Feed
    put:
      tags:
      - feed
      summary: Update an existing feed
      description: Update an existing feed by Id
      operationId: updateFeed
      parameters:
      - name: feedId
        in: path
        description: ID of the feed that needs to be altered
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Update an existent feed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPutFeedExample'
          application/xml:
            schema:
              $ref: '#/components/schemas/PostPutFeedExample'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostPutFeedExample'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
            application/xml:
              schema:
                $ref: '#/components/schemas/Feed'
        "400":
          description: Invalid ID supplied
        "404":
          description: Feed not found
        "405":
          description: Validation exception
      x-swagger-router-controller: Feed
    delete:
      tags:
      - feed
      summary: Delete feed by ID
      operationId: deleteFeed
      parameters:
      - name: feedId
        in: path
        description: ID of the feed that needs to be altered
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successfuly deleted
        "400":
          description: Invalid ID supplied
        "404":
          description: Feed not found
      x-swagger-router-controller: Feed
  /feed:
    get:
      tags:
      - feed
      summary: Get all feeds
      description: Returns all feed information
      operationId: getFeeds
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllFeedExample'
      x-swagger-router-controller: Feed
    post:
      tags:
      - feed
      summary: Add new feed
      description: Add new feed
      operationId: addFeed
      requestBody:
        description: Create new Feed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPutFeedExample'
          application/xml:
            schema:
              $ref: '#/components/schemas/PostPutFeedExample'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostPutFeedExample'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
            application/xml:
              schema:
                $ref: '#/components/schemas/Feed'
        "405":
          description: Invalid input
      x-swagger-router-controller: Feed
components:
  schemas:
    AllFeedExample:
      type: array
      example:
      - id: 72fd104c-4500-4c9c-8b49-223ea1d26d4b
        creatorId: LkxGoU
        name: feedname
        tags:
        - relax
        - chill
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed\
          \ do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim\
          \ ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip\
          \ ex ea commodo consequat."
        visibility: public
        configurations:
        - keyword: music
          quantity: 4
          mode: new
          sources:
          - https://www.youtube.com/channel/UCgzshmpXAc1T30PHQ3Yw2lw
          - https://www.youtube.com/c/MTV
        - keyword: music
          quantity: 4
          mode: new
          sources:
          - https://www.youtube.com/channel/UCgzshmpXAc1T30PHQ3Yw2lw
          - https://www.youtube.com/c/MTV
        raiting:
          raiting: 6.9
          comments:
          - 10/10
          - wow
      - id: 1e1adbf9-fad5-417b-9eed-900146ce65d1
        creatorId: LkxGoU
        name: feedname
        tags:
        - relax
        - chill
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed\
          \ do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim\
          \ ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip\
          \ ex ea commodo consequat."
        visibility: public
        configurations:
        - keyword: music
          quantity: 4
          mode: new
          sources:
          - https://www.youtube.com/channel/UCgzshmpXAc1T30PHQ3Yw2lw
          - https://www.youtube.com/c/MTV
        - keyword: music
          quantity: 4
          mode: new
          sources:
          - https://www.youtube.com/channel/UCgzshmpXAc1T30PHQ3Yw2lw
          - https://www.youtube.com/c/MTV
        raiting:
          raiting: 6.9
          comments:
          - 10/10
          - wow
      - id: 5032011d-6c76-4f49-9829-295f065215a4
        creatorId: LkxGoU
        name: feedname
        tags:
        - relax
        - chill
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed\
          \ do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim\
          \ ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip\
          \ ex ea commodo consequat."
        visibility: public
        configurations:
        - keyword: music
          quantity: 4
          mode: new
          sources:
          - https://www.youtube.com/channel/UCgzshmpXAc1T30PHQ3Yw2lw
          - https://www.youtube.com/c/MTV
        - keyword: music
          quantity: 4
          mode: new
          sources:
          - https://www.youtube.com/channel/UCgzshmpXAc1T30PHQ3Yw2lw
          - https://www.youtube.com/c/MTV
        raiting:
          raiting: 6.9
          comments:
          - 10/10
          - wow
      items:
        $ref: '#/components/schemas/Feed'
    PostPutFeedExample:
      type: object
      properties:
        configurations:
          type: array
          items:
            $ref: '#/components/schemas/FeedConfiguration'
        tags:
          type: array
          example:
          - relax
          - chill
        description:
          type: string
          example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do\
            \ eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim\
            \ ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip\
            \ ex ea commodo consequat."
        visibility:
          type: string
          description: visibility of the feed
          example: public
          enum:
          - public
          - private
        name:
          type: string
          example: Feed name
    Feed:
      type: object
      properties:
        id:
          type: string
          example: e56139c9-ee6f-4775-a581-34ce8c1878e0
        name:
          type: string
          example: Feed name
        creatorId:
          type: string
          example: LkxGoU
        tags:
          type: array
          example:
          - relax
          - chill
        description:
          type: string
          example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do\
            \ eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim\
            \ ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip\
            \ ex ea commodo consequat."
        visibility:
          type: string
          description: visibility of the feed
          example: public
          enum:
          - public
          - private
        configurations:
          type: array
          items:
            $ref: '#/components/schemas/FeedConfiguration'
        raiting:
          $ref: '#/components/schemas/Raiting'
      example:
        raiting:
          raiting: 6.9
          comments:
          - - 10/10
            - wow
          - - 10/10
            - wow
        visibility: public
        configurations:
        - mode: new
          quantity: 4
          sources:
          - https://www.youtube.com/watch?v=eLAHSRmFFzE
          - https://www.youtube.com/watch?v=gxLKrLqXGoM
          keyword: music
        - mode: new
          quantity: 4
          sources:
          - https://www.youtube.com/watch?v=eLAHSRmFFzE
          - https://www.youtube.com/watch?v=gxLKrLqXGoM
          keyword: music
        name: Feed name
        creatorId: LkxGoU
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed\
          \ do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim\
          \ ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip\
          \ ex ea commodo consequat."
        id: e56139c9-ee6f-4775-a581-34ce8c1878e0
        tags:
        - relax
        - chill
      xml:
        name: feed
    FeedConfiguration:
      type: object
      properties:
        keyword:
          type: string
          example: music
        quantity:
          type: integer
          example: 4
        mode:
          type: string
          description: Mode
          example: new
          enum:
          - new
          - random
        sources:
          type: array
          example:
          - https://www.youtube.com/watch?v=eLAHSRmFFzE
          - https://www.youtube.com/watch?v=gxLKrLqXGoM
          items:
            type: string
      example:
        mode: new
        quantity: 4
        sources:
        - https://www.youtube.com/watch?v=eLAHSRmFFzE
        - https://www.youtube.com/watch?v=gxLKrLqXGoM
        keyword: music
      xml:
        name: feedConfiguration
    Raiting:
      type: object
      properties:
        raiting:
          type: number
          example: 6.9
        comments:
          type: array
          items:
            example:
            - 10/10
            - wow
      example:
        raiting: 6.9
        comments:
        - - 10/10
          - wow
        - - 10/10
          - wow
      xml:
        name: raiting
