[tool.isort]
profile = 'black'
line_length = 120
multi_line_output = 3
lines_after_imports = 2
use_parentheses = true
case_sensitive = true
ensure_newline_before_comments = true

known_first_party = 'billing.hot.calculators.trust'
known_secondparty = 'billing.library.python.calculator'
sections = 'FUTURE,STDLIB,THIRDPARTY,SECONDPARTY,FIRSTPARTY,LOCALFOLDER'


[tool.black]
line-length = 120
target-version = ["py38"]
